### ISSUE TITLE
pip install -r linux/tools/labs/requirements.txt - no such file in linux repo

### ISSUE THREAD

**Issue by kathirvalavan** [linux-kernel-labs/docker#2]

**Comment by kathirvalavan** [comment]
@tavip  Thanks for this docker file. helped to setup ubuntu in docker except the last line. is this docker file outdated?

**Comment by tavip** [comment]
@kathirvalavan yes, this repository is outdated. See this PR https://github.com/linux-kernel-labs/linux/pull/164/files in the main repository which adds support for docker.
